management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
          - "refresh"
  endpoint:
    gateway:
      enabled: true
spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: http://localhost:6097
          predicates:
            - Path=/event/**
          filters:
            - RewritePath=/event/(?<path>.*),/$\{path}
